# 베이스 이미지 선택
FROM openjdk:17-jdk-slim

# 작업 디렉토리 설정
WORKDIR /app

# 빌드 인수 정의 (ARG)
ARG SPRING_PROFILES_ACTIVE
ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD
ARG MAIL_HOST
ARG MAIL_PORT
ARG MAIL_USERNAME
ARG MAIL_PASSWORD
ARG DOCKER_HUB_USERNAME

# 환경 변수 설정 (SPRING_PROFILES_ACTIVE)
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
ENV DB_URL=${DB_URL}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV MAIL_HOST=${MAIL_HOST}
ENV MAIL_PORT=${MAIL_PORT}
ENV MAIL_USERNAME=${MAIL_USERNAME}
ENV MAIL_PASSWORD=${MAIL_PASSWORD}
ENV DOCKER_HUB_USERNAME=${DOCKER_HUB_USERNAME}

# 빌드된 JAR 파일을 컨테이너에 복사
COPY build/libs/*.jar app.jar
# 컨테이너가 실행될 때 실행할 명령어
ENTRYPOINT ["java", "-jar", "app.jar"]
